src/inventory/urls.py
from django.urls import path
from .views import (
    materials_view,
    material_detail_view,
    add_material_view,
    create_transaction,
    transactions_view,
    materials_abc_view,
    materials_xyz_view,
    get_filter_options,
    get_sales_chart
)

from .air_views import airflow_table_view, airflow_agg_view

app_name = "inventory"

urlpatterns = [
    path("materials/", materials_view, name="materials"),
    path("material/<int:material_id>/", material_detail_view, name="material"),
    path("add-material/", add_material_view, name="add_material"),
    path("transactions/", transactions_view, name="transactions"),
    path("create-transaction/", create_transaction, name="create_transaction"),
    path("material-abc-stats/", materials_abc_view, name="materials_abc_stats"),
    path("material-xyz-stats/", materials_xyz_view, name="materials_xyz_stats"),
    path("filter-options/", get_filter_options, name="chart-filter-options"),
    path("sales/<int:year>/<int:material_id>/", get_sales_chart, name="chart-sales"),

    path("airflow-table/", airflow_table_view, name="airflow_table"),
    path("airflow-analyzed/", airflow_agg_view, name="airflow_analyzed"),
]

src/stocks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("auth/", include("users.urls", namespace="auth")),
]

src/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, profile_view


app_name = 'auth'

urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile_view, name="profile"),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}My Site{% endblock %}</title>
	<script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.6.4.min.js"
      integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8="
      crossorigin="anonymous">
    </script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Stock Manager</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            	<li class="nav-item dropdown">
					<a
					class="nav-link dropdown-toggle"
					href="#"
					id="navbarDropdown"
					role="button"
					data-bs-toggle="dropdown"
					aria-expanded="false"
					>
                  		Materials
                	</a>
                	<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li>
							<a
							class="dropdown-item"
							href="{% url 'inventory:materials' %}"
							>Materials</a
							>
						</li>
						<li>
							<a
								class="dropdown-item"
								href="{% url 'inventory:add_material' %}"
							>Add a material</a>
						</li>
                	</ul>
              	</li>

              	<li class="nav-item dropdown">
                	<a
                  	class="nav-link dropdown-toggle"
					href="#"
					id="navbarDropdown"
					role="button"
					data-bs-toggle="dropdown"
					aria-expanded="false"
                	>
                  		Transactions
                	</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li>
							<a
							class="dropdown-item"
							href="{% url 'inventory:transactions' %}"
							>Transactions</a
							>
						</li>
						<li>
							<a
							class="dropdown-item"
							href="{% url 'inventory:create_transaction' %}"
							>Create a transaction</a
							>
						</li>
					</ul>
              	</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'inventory:materials_abc_stats' %}">Stats ABC</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'inventory:materials_xyz_stats' %}">Stats XYZ</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'inventory:airflow_table' %}">API Based Table</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'inventory:airflow_analyzed' %}">API Based Analyze</a>
				</li>
            </ul>
			<span class="navbar-text ms-auto">
				{% if request.user.is_authenticated %}
				<a href="{% url 'auth:profile' %}">Profile</a>
				{% else %}
				<a href="{% url 'auth:register' %}">Register</a>
				<a class="ms-3" href="{% url 'auth:login' %}">Login</a>
				{% endif %}
			</span>
			{% if request.user.is_authenticated %}
			<form method="post" action="{% url 'auth:logout' %}">
				{% csrf_token %}
				<button type="submit" class="dropdown-item text-danger ms-3">Log out</button>
			</form>
			{% endif %}
          </div>
        </div>
      </nav>
    </div>
	{% if messages %}
	<div class="container mt-3">
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
			{{ message }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
		{% endfor %}
	</div>
	{% endif %}
    <div class="container mt-4">{% block content %} {% endblock %}</div>
	{% block scripts %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>