src/inventory/urls.py
from django.urls import path
from .views import (
    materials_view,
    material_detail_view,
    add_material_view,
    create_transaction,
    transactions_view,
    materials_abc_view,
    materials_xyz_view,
    get_filter_options,
    get_sales_chart
)

from .air_views import airflow_table_view, airflow_agg_view

app_name = "inventory"

urlpatterns = [
    path("materials/", materials_view, name="materials"),
    path("material/<int:material_id>/", material_detail_view, name="material"),
    path("add-material/", add_material_view, name="add_material"),
    path("transactions/", transactions_view, name="transactions"),
    path("create-transaction/", create_transaction, name="create_transaction"),
    path("material-abc-stats/", materials_abc_view, name="materials_abc_stats"),
    path("material-xyz-stats/", materials_xyz_view, name="materials_xyz_stats"),
    path("filter-options/", get_filter_options, name="chart-filter-options"),
    path("sales/<int:year>/<int:material_id>/", get_sales_chart, name="chart-sales"),

    path("airflow-table/", airflow_table_view, name="airflow_table"),
    path("airflow-analyzed/", airflow_agg_view, name="airflow_analyzed"),
]

src/stocks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("auth/", include("users.urls", namespace="auth")),
]

src/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, profile_view


app_name = 'auth'

urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile_view, name="profile"),
]

src/inventory/models.py
from django.db import models
from users.models import Profile


class Material(models.Model):
    class Unit(models.TextChoices):
        LITRE = 'l', 'litre'
        KILOGRAM = 'kg', 'kg'
        M2 = 'm2', 'm²'
        PIECE = 'pcs', 'piece'
        PACK = 'pack', 'pack'
    name = models.CharField(max_length=100)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    unit = models.CharField(max_length=10, choices=Unit.choices)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    company = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.name} - {self.unit}'


class Transaction(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    company = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_type = models.CharField(
        max_length=3, choices=[("IN", "Incoming"), ("OUT", "Outgoing")]
    )
    date = models.DateField()


class MaterialInfo(models.Model):
    class ABC(models.TextChoices):
        A = 'A', 'A'
        B = 'B', 'B'
        C = 'C', 'C'

    class XYZ(models.TextChoices):
        X = 'X', 'X'
        Y = 'Y', 'Y'
        Z = 'Z', 'Z'

    material = models.OneToOneField(Material, on_delete=models.CASCADE)
    abc_group = models.CharField(max_length=1, choices=ABC.choices)
    xyz_group = models.CharField(max_length=1, choices=XYZ.choices)

src/inventory/forms.py
from django import forms
from .models import Material, Transaction


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ["name", "unit_price", "unit", "quantity"]


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ["material", "quantity", "transaction_type", "date"]
        widgets = {"date": forms.DateInput(attrs={"type": "date"})}

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)
        if self.request:
            self.fields["material"].queryset = Material.objects.filter(
                company=self.request.user.profile
            )

src/inventory/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.core.exceptions import ValidationError
from django.db.models import F, Sum
from django.db.models.functions import TruncMonth, ExtractYear, ExtractMonth
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Material, Transaction
from .forms import MaterialForm, TransactionForm
from .filters import TransactionFilter, MaterialFilter
from utils.transaction_helper import check_transaction
from utils.abc_analysis_helper import get_abc_statistics
from utils.xyz_analisis_helper import get_xyz_statistics
from utils.chart_helper import months, get_year_dict, colorPrimary


@login_required
def materials_view(request):
    materials = Material.objects.filter(company=request.user.profile)
    my_filter = MaterialFilter(request.GET, queryset=materials)
    materials = my_filter.qs
    return render(request, "inventory/materials.html", {"materials": materials})


@login_required
def material_detail_view(request, material_id):
    material = get_object_or_404(Material, id=material_id, company=request.user.profile)
    return render(request, "inventory/material.html", {"material": material})


@login_required
def add_material_view(request):
    if request.method == "POST":
        form = MaterialForm(request.POST)
        if form.is_valid():
            material = form.save(commit=False)
            material.company = request.user.profile
            material.save()
            messages.success(request, "Material has been added")
            return redirect("inventory:materials")
    form = MaterialForm()
    return render(request, "inventory/add_material.html", {"form": form})


@login_required
def transactions_view(request):
    transactions = Transaction.objects.filter(company=request.user.profile)
    my_filter = TransactionFilter(request.GET, queryset=transactions)
    transactions = my_filter.qs
    return render(
        request,
        "inventory/transactions.html",
        {"transactions": transactions, "my_filter": my_filter},
    )


@login_required
def create_transaction(request):
    if request.method == "POST":
        form = TransactionForm(data=request.POST, request=request)
        if form.is_valid():
            try:
                check_transaction(
                    form.cleaned_data["material"],
                    form.cleaned_data["quantity"],
                    form.cleaned_data["transaction_type"],
                )
                transaction = form.save(commit=False)
                transaction.company = request.user.profile
                transaction.save()
                messages.success(request, "Transaction has been created")
                return redirect("inventory:materials")
            except ValidationError as e:
                form.add_error(None, list(e))
    else:
        form = TransactionForm(request=request)
    return render(request, "inventory/add_transaction.html", {"form": form})


@login_required
def materials_abc_view(request):
    queryset = (
        Material.objects.filter(
            company=request.user.profile, transaction__transaction_type="OUT"
        )
        .annotate(
            ttl_amount_pu=Sum("transaction__quantity"),
            ttl_expenses_pu=Sum("transaction__quantity") * F("unit_price"),
        )
        .values("id", "name", "unit", "ttl_amount_pu", "ttl_expenses_pu")
        .order_by("-ttl_expenses_pu")
    )

    calculated_data = get_abc_statistics(queryset)
    if request.method == "POST":
        response = HttpResponse(content_type="application/ms-excel")
        response["Content-Disposition"] = "attachment; filename=data.xlsx"
        calculated_data.to_excel(response, index=False, engine="openpyxl")
        return response
    return render(
        request,
        "inventory/materials_abc_stats.html",
        {"pd_data": calculated_data.to_dict(orient="records")},
    )


@login_required
def materials_xyz_view(request):
    queryset = (
        Material.objects.filter(
            company=request.user.profile,
            transaction__transaction_type="OUT"
        )
        .annotate(
            month_datetime=TruncMonth("transaction__date"),
        )
        .values(
            "id", "name", "unit", "month_datetime"
        )
        .annotate(
            ttl_amount_pu=Sum("transaction__quantity"),
        )
    )

    calculated_data = get_xyz_statistics(queryset)
    if request.method == "POST":
        response = HttpResponse(content_type="application/ms-excel")
        response["Content-Disposition"] = "attachment; filename=data.xlsx"
        calculated_data.to_excel(response, index=False, engine="openpyxl")
        return response
    return render(
        request,
        "inventory/materials_xyz_stats.html",
        {"pd_data": calculated_data.to_dict(orient="records")},
    )


@login_required
def get_filter_options(request):
    grouped_purchases = (
        Material.objects.annotate(year=ExtractYear("transaction__date"))
        .values("year")
        .order_by("-year")
        .distinct()
    )
    options = [purchase["year"] for purchase in grouped_purchases]

    return JsonResponse(
        {
            "options": options,
        }
    )


@login_required
def get_sales_chart(request, year, material_id):
    queryset = (
        Material.objects.filter(
            id=material_id,
            company=request.user.profile,
            transaction__transaction_type="OUT"
        )
        .annotate(
            month_datetime=TruncMonth("transaction__date"),
            month=ExtractMonth("transaction__date")
        )
        .values(
            "id", "name", "unit", "month_datetime", "month"
        )
        .annotate(
            ttl_amount_pu=Sum("transaction__quantity"),
        )
    )
    sales_dict = get_year_dict()

    for group in queryset:
        sales_dict[months[group["month"] - 1]] = group["ttl_amount_pu"]

    return JsonResponse(
        {
            "title": f"Sales in {year}",
            "data": {
                "labels": list(sales_dict.keys()),
                "datasets": [
                    {
                        "label": "Quantity",
                        "backgroundColor": colorPrimary,
                        "borderColor": colorPrimary,
                        "data": list(sales_dict.values()),
                    }
                ],
            },
        }
    )

src/inventory/templates/inventory/add_material.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Add a MATERIAL</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Add</button>
</form>
{% endblock content %}

src/inventory/templates/inventory/add_transaction.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Create a TRANSACTION</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock content %}

src/inventory/templates/inventory/m_comp.html
{% extends 'base.html' %} 

{% block content %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">id</th>
      <th scope="col">order id</th>
      <th scope="col">material id</th>
      <th scope="col">quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for material in m_comp %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ material.id }}</a></td>
      <td>{{ material.order }}</td>
      <td>{{ material.material }}</td>
      <td>{{ material.quantity }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/inventory/templates/inventory/material.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<div class="row">
  <div class="col-sm-4">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Name: {{ material.name }}</li>
      <li class="list-group-item">Price: {{ material.unit_price }}</li>
      <li class="list-group-item">Current quantity: {{ material.quantity }}</li>
      <li class="list-group-item">Unit: {{ material.unit }}</li>
    </ul>
  </div>

  <div class="col-sm-8">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button
          class="nav-link active"
          id="history-tab"
          data-bs-toggle="tab"
          data-bs-target="#history"
          type="button"
          role="tab"
          aria-controls="history"
          aria-selected="true"
        >
          History
        </button>
      </li>
      <li class="nav-item" role="presentation">
        <button
          class="nav-link"
          id="profile-tab"
          data-bs-toggle="tab"
          data-bs-target="#profile"
          type="button"
          role="tab"
          aria-controls="profile"
          aria-selected="false"
        >
          Statistics
        </button>
      </li>
      <li class="nav-item" role="presentation">
        <button
          class="nav-link"
          id="contact-tab"
          data-bs-toggle="tab"
          data-bs-target="#contact"
          type="button"
          role="tab"
          aria-controls="contact"
          aria-selected="false"
        >
          Contact
        </button>
      </li>
    </ul>
    <div class="tab-content container" id="myTabContent">
      <div
        class="tab-pane fade show active"
        id="history"
        role="tabpanel"
        aria-labelledby="history-tab"
      >
	  	<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Material</th>
					<th scope="col">Quantity</th>
					<th scope="col">Transaction type</th>
					<th scope="col">Date</th>
				</tr>
			</thead>
			<tbody>
				{% for transaction in material.transaction_set.all %}
				<tr {% if transaction.transaction_type == "IN" %}class="table-success"{% else %}class="table-danger"{% endif %}>
					<th scope="row">{{ forloop.counter }}</th>
					<td>{{ transaction.material }}</td>
					<td>{{ transaction.quantity }}</td>
					<td>{{ transaction.transaction_type }}</td>
					<td>{{ transaction.date }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
      </div>
      <div
        class="tab-pane fade"
        id="profile"
        role="tabpanel"
        aria-labelledby="profile-tab"
      >
	  <div class="container mt-3" id="chartContainer" data-material-id="{{ material.id }}">
		<form id="filterForm" class="d-flex align-items-center gap-2">
		  <label for="year" class="me-2 mb-0">Choose a year:</label>
		  <select class="form-select w-auto" name="year" id="year"></select>
		  <input class="btn btn-primary" type="submit" value="Load" name="_load">
		</form>
		<canvas id="salesChart" class="mt-4"></canvas>
	  </div>
	  
      </div>
      <div
        class="tab-pane fade"
        id="contact"
        role="tabpanel"
        aria-labelledby="contact-tab"
      >
        ...
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
  <script src="{% static 'js/inventory_charts.js' %}"></script>
{% endblock %}

src/inventory/templates/inventory/materials.html
{% extends 'base.html' %}

{% block content %}
<form class="d-flex">
    <input class="form-control me-2" name="name" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Price per unit</th>
      <th scope="col">Unit of measurment</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for material in materials %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url 'inventory:material' material.id %}">{{ material.name }}</a></td>
      <td>{{ material.unit_price }}</td>
      <td>{{ material.unit }}</td>
      <td>{{ material.quantity }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/inventory/templates/inventory/materials_abc_stats.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <button class="btn btn-primary" type="submit">Download report (.xlsx)</button>
</form>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Unit of measurment</th>
      <th scope="col">Total amount</th>
      <th scope="col">Total expenses</th>
      <th scope="col">Percent</th>
      <th scope="col">Cumulative Percent</th>
      <th scope="col">ABC Category</th>
    </tr>
  </thead>
  <tbody>
    {% for item in pd_data %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.name }}</td>
      <td>{{ item.unit }}</td>
      <td>{{ item.ttl_amount_pu }}</td>
      <td>{{ item.ttl_expenses_pu }}</td>
      <td>{{ item.percent }}</td>
      <td>{{ item.cumulative_percent }} %</td>
      <td>{% if item.cumulative_percent < 80 %}A{% elif item.cumulative_percent < 95 %}B{% else %}C{% endif %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/inventory/templates/inventory/materials_cons_agg.html
{% extends 'base.html' %} 

{% block content %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Material name</th>
      <th scope="col">Date</th>
      <th scope="col">Units</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for material in data %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ material.material__name }}</a></td>
      <td>{{ material.date }}</td>
      <td>{{ material.material__unit }}</td>
      <td>{{ material.total_quantity }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/inventory/templates/inventory/materials_consumption.html
{% extends 'base.html' %} 

{% block content %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">id</th>
      <th scope="col">Order</th>
      <th scope="col">Material</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for material in m_cons %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ material.id }}</a></td>
      <td>{{ material.order }}</td>
      <td>{{ material.material }}</td>
      <td>{{ material.quantity }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/inventory/templates/inventory/materials_xyz_stats.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <button class="btn btn-primary" type="submit">Download report (.xlsx)</button>
</form>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Average expenses</th>
      <th scope="col">Standart deviation</th>
      <th scope="col">Variance</th>
      <th scope="col">XYZ Category</th>
    </tr>
  </thead>
  <tbody>
    {% for item in pd_data %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.name }}</td>
      <td>{{ item.avg }}</td>
      <td>{{ item.std_dev }}</td>
      <td>{{ item.cv }}</td>
      <td>{% if item.cv < 0.10 %}X{% elif item.cv < 0.25 %}Y{% else %}Z{% endif %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/inventory/templates/inventory/transactions.html
{% extends 'base.html' %} 

{% block content %}
<button
  type="button"
  class="btn btn-primary"
  data-bs-toggle="modal"
  data-bs-target="#exampleModal"
>
  Filters
</button>

<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Set up filters</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
	  <form method="get">
      <div class="modal-body">
          Start date:
          <input type="date" class="form-control" name="date__gte" value="{{ request.GET.date__gte }}"/>
          End date:
          <input type="date" class="form-control" name="date__lte" value="{{ request.GET.date__lte }}"/>
          Type:
          <select class="form-select" name="transaction_type">
            <option value="">All</option>
            <option value="IN">In</option>
            <option value="OUT">Out</option>
          </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
		<button class="btn btn-primary" type="submit">Filter</button>
      </div>
	</form>
    </div>
  </div>
</div>

<table class="table table-striped">
	<thead>
	  <tr>
			<th scope="col">#</th>
			<th scope="col">Material</th>
			<th scope="col">Quantity</th>
			<th scope="col">Transaction type</th>
			<th scope="col">Date</th>
	  </tr>
	</thead>
	<tbody>
	  {% for transaction in transactions %}
	  <tr {% if transaction.transaction_type == "IN" %}class="table-success"{% else %}class="table-danger"{% endif %}>
			<th scope="row">{{ forloop.counter }}</th>
			<td>{{ transaction.material }}</td>
			<td>{{ transaction.quantity }}</td>
			<td>{{ transaction.transaction_type }}</td>
			<td>{{ transaction.date }}</td>
	  </tr>
	  {% endfor %}
	</tbody>
</table>
{% endblock content %}